- README.md
This commit corrects the scripts which states
ocs operator -> odf must-gather
Signed-off-by: yati1998 <ypadia@redhat.com>
> correct ocs -> odf must-gather in the code

- .github/workflows/odf-must-gather-ci.yaml
This commit adds basic codespell and shellcheck
to ci.
Signed-off-by: yati1998 <ypadia@redhat.com>
> ci: adds coodespell and shellcheck to github

- OWNERS
This commit add @yati1998 to owners file
and also shifts the owner file to the main
folder.
Signed-off-by: yati1998 <ypadia@redhat.com>
> add yati1998 to owner file

- must-gather/collection-scripts/gather_ceph_resources
The call to 'crash_core_collection' was incorrect.
> Fix the call to crash_core_collection function.

- CONTRIBUTING.md
- README.md
- must-gather/collection-scripts/pre-install.sh
This patch removes the redundant sections, broken links and references to ocs-operator specific commands from different parts of the documentations.
> must-gather: Docs cleanup

- must-gather/collection-scripts/gather_ceph_resources
In addition to `rbd info` and `rbd snap ls --all`, collect the output of `rbd status` too.
See-also: https://bugzilla.redhat.com/2215917
> Bug 2215917: collect the status for RBD-images

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_clusterscoped_resources
- must-gather/collection-scripts/gather_common_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/gather_noobaa_resources
- must-gather/collection-scripts/pre-install.sh
- must-gather/collection-scripts/utils.sh
Using echo and then piping it to a log file is a pattern that can be seen throughout this project. Doing so requires quite a log of syntax.
The idea is to have a file with common utility functions and source them at the beginning of the run.
We already pass `BASE_COLLECTION_PATH` as an argument to every script so this approach is just building on top of that.
Another fix included in this patch is for out of scope variable reference at preinstall.sh:29. Shell scripts do not carry over variable definitions.
> Gather: Use utility function to append to debug logs

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_clusterscoped_resources
- must-gather/collection-scripts/gather_common_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/gather_noobaa_resources
- must-gather/collection-scripts/pre-install.sh
And its resolution in case it is not defined. We never call any of the collection scripts without them expecting basepath unless being called explicitly from the container.
In that case, it will resolve to PWD and the script will execute as expected without any overlaps as exported shell variables have a TTL until they are subprocesses of the current shell.
> Improve handling of BASE_COLLECTION_PATH

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_clusterscoped_resources
- must-gather/collection-scripts/gather_common_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/gather_noobaa_resources
- must-gather/collection-scripts/post-uninstall.sh
- must-gather/collection-scripts/pre-install.sh
This approach is preferred on systems where the path of the interpreter might not be the one we defined.
We do not use interpreter args anywhere in this project and hence this patch can be applied as a drop-in replacement. This makes the project more portable and in sync with OpenShift mg.
> Use ENV to determine the interpreter path

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_clusterscoped_resources
- must-gather/collection-scripts/gather_common_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/gather_noobaa_resources
Optimize `SINCE_TIME` access by exporting it as a variable. Saves us from passing it around and manually accessing it.
> Export SINCE_TIME for use in sub scripts

- must-gather/collection-scripts/gather_namespaced_resources
This commit removes the sort-by flag from
oc describe events collection
> remove sort-by flag from events desc

- collection-scripts/gather_noobaa_resources
For the noobaa's postgres pod, also copy the log directory.
> Copy postgres log files for noobaa/mcg

- Makefile
Fixes: #77 
Note: You still need to export `ODF_MG_TOKEN`.
Example: `ODF_MG_TOKEN=<MY_TOKEN_HERE> make local`
This builds and tags the image as "odf-mg". You can override it using `IMG_TAG` environment variable.
P.S: If using rancher, just export RANCHER variable in the ENV.
Extended example: `RANCHER=yes ODF_MG_TOKEN=<TOKEN_HERE> IMG_TAG=my-custom-tag make local`
Regards
> [Makefile] Allow local builds by using `make local`

- collection-scripts/gather_main
We need not call provider script in default mod, so removing it from the main call.
We also need to collect ceph_logs in default op,
it was missing
> remove provider call in default op mode

- collection-scripts/gather
Supposed to be used in conjunction with other args as it makes no sense to use it standalone. Passing `-o` or `--odf` will include the data from `deafult` op mode along with other data requested by the remaining args.
> Add arg for collecting ODF logs

- collection-scripts/gather
https://bugzilla.redhat.com/show_bug.cgi?id=2265340
When you run must gather command with help flag [-h or --help], you expect to understand the parameters of the command. we don't need to run pre-install.sh script 
https://github.com/red-hat-storage/odf-must-gather/blob/main/collection-scripts/gather#L131
I created a PR to fix it and tested it with a private image https://github.com/red-hat-storage/odf-must-gather/pull/119
official/dev-image output:
```
$ oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.15  -- /usr/bin/gather --help  
[must-gather      ] OUT Using must-gather plug-in image: quay.io/rhceph-dev/ocs-must-gather:latest-4.15
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested …
```
> No need to call pre-install script for help flag

- collection-scripts/gather_ceph_resources
- collection-scripts/gather_namespaced_resources
This commit collects crds and few resources for
openshift-storage-extended namespace
> collect resources for openshift-storage-extended ns

- README.md
- collection-scripts/gather
- collection-scripts/gather_ceph_resources
- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_odf_client
PR containing the latest commits from main branch
> Syncing latest changes from main for odf-must-gather

- collection-scripts/gather
- collection-scripts/gather_ceph_resources
- collection-scripts/gather_clusterscoped_resources
- collection-scripts/gather_common_ceph_resources
- collection-scripts/gather_dr_resources
- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_noobaa_resources
- collection-scripts/gather_odf_client
According to the spec oc cli expects the args to inspect
in the format: `oc adm inspect <args> <resource>`
Adapt the project according to the spec.
This patch also removes `SINCE_TIME` var as it served no purpose in its current form.
Regards
> Fix order of args supplied to oc adm inspect

- collection-scripts/gather
- collection-scripts/gather_ceph_logs
- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_noobaa_resources
- collection-scripts/gather_odf_client
- collection-scripts/utils.sh
The must-gather now filters its logs based on the above parameters. The said parameters are provided by the OC cli as ENV values.
> Add support for --since and --since-time flags

- collection-scripts/gather_ceph_resources
- collection-scripts/gather_clusterscoped_resources
- collection-scripts/gather_common_ceph_resources
- collection-scripts/gather_dr_resources
- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_noobaa_resources
- collection-scripts/gather_odf_client
In cases where `LOG_FILTER_ARGS` was unset/empty, an empty string was interpreted by bash breaking the oc commands.
This patch addresses the issue by expanding only when the value is set. If unset, an empty space is used instead of empty string. ` ` instead of `' '`.
Regards
> Fix error in expansion of SINCE_TIME

- Dockerfile
Old image had various warnings with outdated deps. This image has none.
Source: See quay reports on image security.
> Use 4.16 images as base for image builds

- collection-scripts/gather
Currently the default and odf mode collects all the resouces. This commit segregates the odf mode
from default mode.
> segregate odf collection from default

- collection-scripts/gather_odf_client
after storageclient being clusterscoped
the logs for client cluser were not getting collected. This commit adds the changes to include all the logs and other resources
> collect client logs with proper namespace

- collection-scripts/gather_namespaced_resources
There was a typo in one of the sub-scripts which lead to failing GH Action runs. This patch fixes the same.
> Fix GH action failing due to typo

- collection-scripts/gather
Fixes: #137
Right now if someone runs must-gather in odf mode
by using `-o` or `--odf` flag and also issues one
of `-c`, `-cl`, `-ns` or `-cs`, these scripts will be executed twice,
adding to the collection time and creating redundant collection.
This patch prevents execution of any of the sub-scripts that are already called by `-o` flag.
> Negate overlapping args with `-o` flag

- collection-scripts/gather
odf flag fails to collect proper logs in case
of radosnamespace due to absence of
BASE_COLLECTION_PATH.
> pass the BASE_COLLECTION_PATH for odf collection

- collection-scripts/gather_ceph_logs
added the csi log to a csi log directory csi_log_${node}
Also updated correct dir path to cllect the ceph daemon logs
closes: https://github.com/red-hat-storage/odf-must-gather/issues/178
> csi: add logrotate file to a csi log dir

- templates/pod.template
This PR updates the ImagePullPolicy for the must-gather pod to Always.
This adds value to the development phase where one can just delete the pod and have an updated one with the latest image.
Prior to this one had to use different tags for each test which was not ideal.
Note: This would not increase pod deploy timinigs in prod env as we do not update the prod image that often and ImagePullPolicy of always first checks the SHA sum from registry against local cache.
If the image is cached locally, it is not pulled again.
> Update ImagePullPolicy to Always

- collection-scripts/gather
- collection-scripts/utils.sh
This PR adds support of fetching the pod metadata
using the kubernetes API.
An additional pod-metadata.json file is created in the report with the dump of entire metadata for the pod.
A much simpler debug log stating the image version being used is printed to the console as well.
The image details are printed to console like:
```
[must-gather      ] OUT 2024-08-07T15:21:19.386616439Z namespace/openshift-must-gather-8452x created
[must-gather      ] OUT 2024-08-07T15:21:19.39445305Z clusterrolebinding.rbac.authorization.k8s.io/must-gather-jkbhm created
[must-gather      ] OUT 2024-08-07T15:21:19.429835897Z pod for plug-in image quay.io/niryadav/odf-must-gather:infot7 created
[must-gather-2d5hn] POD 2024-08-07T15:21:26.932423529Z volume percentage checker started.....
[must-gather-2d5hn] …
```
> Include pod metadata in must-gather output

- collection-scripts/gather_ceph_logs
currently client operator has started using csi operator so collecting the csi logs from a new host path
hat csi-operator supports
> Bug 2308101: logrotate: add logrotate functionality for csi operator

- collection-scripts/gather_ceph_logs
currently client operator has started using csi operator
so collecting the csi logs from a new host path
hat csi-operator supports
Signed-off-by: parth-gr <partharora1010@gmail.com>
(cherry picked from commit https://github.com/red-hat-storage/odf-must-gather/commit/799c77a94ae2c61e732f4f8cb031555c310cfc4b)
> Bug 2308101: logrotate: add logrotate functionality for csi operator 

- collection-scripts/gather_ceph_logs
This PR adds the missing PIDs for subprocesses
while collecting ceph logs.
> Add missing PIDs while collecting ceph logs

- collection-scripts/gather
- collection-scripts/gather_minimal_resources
Creating a flag to limit data collection to only major CRDs and CSVs, reducing time taken and log clutter.
It collects minimum required data and have kept the alignment similar to other flags for streamlined parsing.
> Add new flag to collect minimal resources

- collection-scripts/gather
The patch modifies the collection time
to not include the time taken by the
preinstall script.
Closes: #136
> Fix collection time

- collection-scripts/gather_namespaced_resources
This patch adds a script that parses and strips of extraneous info from the `rook-ceph-external-cluster-details` secret.
This secret is namespaced to the ODF install namespace.
> DFBUGS-727: gather: Add a script to collect external cluster details

- collection-scripts/gather
The MG currently uses `-empty` with find to remove the empty files. This only works for files with a
size of 0 bytes.
In cases where the file has an empty line or a single character this doesn't work.
This patch updates the logic to also consider files with LF endings (just a new line)
> gather: Fix removal of empty files from gather

- collection-scripts/gather_common_ceph_resources
This patch adds support for collection of CephBlockPoolRadosNamespaces in external mode deployments.
> ceph: Collect CephBlockPoolRadosNamespace(s) in external deployments

- collection-scripts/gather_noobaa_resources
this commit removes the hard-coded namespace
for noobaa collection to collect all the
resources in correct namespace
> remove hard-coded namespace from noobaa

- templates/pod.template
Fixes an issue where the must-gather toolbox pod fails with a read-only filesystem error when writing to `/etc/ceph/ceph.conf` and `/etc/ceph/keyring`
> Add emptyDir volume mount for /etc/ceph to allow write access in helper pod

- collection-scripts/gather_noobaa_resources
- collection-scripts/utils.sh
For 4.19 CNPG integration in noobaa - added collection of cnpg information in `gather_noobaa_resources` script
collecting the following information:
* `describe` output for the new cluster pods. Keeping the description of older resources on purpose, for upgrade issues. 
* Using the CNPG CLI (copied from the cnpg operator pod), get the status and reports for the operator and the cluster
* Get `pg_stat_statements` statistics, which are now collected by default.
> collect cnpg cluster info in gather_noobaa_resources

- collection-scripts/gather_ceph_logs
The directory creation was incorrectly removed by #248 
This patch restores the directory creation and removes the unnecessary coredump dir.
> gather_ceph_logs: Fix crash output dir creation

- collection-scripts/gather_dr_resources
in case of dr collection we collect pods -owide
as dr resource, but must-gather takes pods and -owide as different resources, resulting in error.
`collecting oc command -owide
You must specify the type of resource to get.
Use "oc api-resources" for a complete list of
supported resources.`
> error collecting pod details

- collection-scripts/gather_noobaa_resources
Remove extra `}` from:
```
mkdir -p "${NOOBAA_COLLLECTION_PATH}/raw_output/}"
```
This fixes the path so it correctly creates `/noobaa/raw_output/` without generating an unintended `}/` folder.
Fixes: #282
> fix: remove extra '}' from mkdir path in NooBaa collection

- collection-scripts/gather_namespaced_resources
This commit removes the storagesystem CR as
it has been removed from ODF4.19 onwards.
> remove storagesystem CR from collection
