red-hat-storage/odf-must-gather

- .github/workflows/odf-must-gather-ci.yaml
- must-gather/OWNERS
This commit adds approvers and reviewers
for odf-must-gather repo.
Signed-off-by: yati1998 <ypadia@redhat.com>
> adds owner details in repo

- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/pre-install.sh
this commit removes the label so that must gather
can collect logs from all nodes irrespective of
what label it has.
> removes label to collect logs from all nodes

- must-gather/collection-scripts/gather_ceph_resources
This commit resolves jq not found error
> cleanup to resolve jq: command not found error

- CONTRIBUTING.md
- DCO
Adding the Developer Certificate of Origin file.
> must-gather: Add DCO file

- must-gather/collection-scripts/gather_namespaced_resources
This commit collects logs for manager-
fusionoffering CR for managedservices.
> collect logs for managedfusionoffering CR

- must-gather/collection-scripts/gather_noobaa_resources
Adding namespacestore in noobaa collection_script
> Adding namespacestore in noobaa collection_script

- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_clusterscoped_resources
- must-gather/collection-scripts/gather_common_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/gather_noobaa_resources
- must-gather/collection-scripts/pre-install.sh
- must-gather/functests/integration/command_output_test.sh
Replaced the checks for null and non-null values with bash builtin `-z` and `-n` respectively.
> Use bash expressions to check for null/non-null

- must-gather/collection-scripts/gather
- must-gather/collection-scripts/gather_ceph_resources
- must-gather/collection-scripts/gather_namespaced_resources
- must-gather/collection-scripts/pre-install.sh
Throughout the project we have used test experssions to compare, pattern matching was used in few places. Replaced that with test experssions to be more consistent and portable.
> Defer pattern matching

- must-gather/collection-scripts/gather_namespaced_resources
This commit is to collect the events in
sorted order and also collect yamls and describe
of oc events resource
> collect events in a sorted order

- must-gather/collection-scripts/gather_namespaced_resources
Reverts red-hat-storage/odf-must-gather#61
> Revert "Revert "Bug: 2218309 The NAD collection code appears twice [on release-4.14 branch]""

- must-gather/collection-scripts/gather_namespaced_resources
and add missing space after the namespace flag.
> [gather-ns-resources] Delimit BASE_COLLECTION_PATH

- .github/workflows/odf-must-gather-ci.yaml
...errors resulting due to new directory structure.
> [ci] Fix github workflows

- README.md
*
The image pointed to did not exist.
*
> Fix readme to point to correct must gather image

- README.md
> [Doc] Update README for local builds using make

- README.md
This commit adds more details on how to use
the modularized must-gather to README
> add documentation to README

- collection-scripts/gather_main
This patches addresses the issue of default op mode taking longer to finish and the errors related to handling of helper pod.
Regards
> Support parallel collection in default op mode

- collection-scripts/gather_dr_resources
Tested with my image:
```
oc adm must-gather --image=quay.io/oviner/ocs-must-gather:dr_hub_mg -- /usr/bin/gather -d
```
```
$ pwd
/home/oviner/ClusterPath/auth/dr_mg
$ ls
openshift-operators
```
> Add option to collect logs in hub cluster

- collection-scripts/gather_odf_client
this commit includes csidriver details in
odfclient collection
> collect csidriver details for odf-client

- README.md
- collection-scripts/gather
> Fix Readme file, seems that you can run the gather command without the "oc adm must gather"

- README.md
- collection-scripts/gather
> Fix Noobaa typos

- README.md
Discussed here: https://issues.redhat.com/browse/OCSDOCS-1448
> Update README for new args

- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_odf_client
This commit includes the name changes made to the
storageclassclaim and storageclassrequest apis.
storageclassclaims -> storageclaim
storageclassrequest -> storagerequest
> include api changes for storageclassclaim and request

- collection-scripts/gather
- collection-scripts/gather_ceph_resources
- collection-scripts/gather_namespaced_resources
PR containing the latest commits from main branch
> Syncing latest changes from main for odf-must-gather

- collection-scripts/gather_noobaa_resources
* provides information on different psql tables and their sizes
> List postgresql tables with extra info in noobaa script

- collection-scripts/gather_namespaced_resources
This patch adds support for collecting EncryptionKeyRotation job and cronjob resources.
> Collect EncryptionKeyRotation resources

- collection-scripts/gather_namespaced_resources
this commit collects new crds details which
are newly created by ceph-csi-operator
> add new crds created by ceph csi operation

- Dockerfile
- Makefile
This patch fixes the failing local builds and
also cleans up the Dockerfile
> build: Fix local builds and cleanup Dockerfile

- Dockerfile
This PR updates the base from 4.16 to 4.17
NOTE: Merge after #198
> build: Use 4.17 images as base

- collection-scripts/gather_dr_resources
- collection-scripts/gather_namespaced_resources
At the development team's request, we have added the [openshift-dr-op] namespace, and we will collect data from it if it exists. https://bugzilla.redhat.com/show_bug.cgi?id=2291180
> Add openshift-dr-ops namespce to DR collection script

- collection-scripts/gather_clusterscoped_resources
this commit collects storageclusterpeers
to clusterscope collection
> include storageclusterpeer info

- collection-scripts/gather_ceph_resources
this commit discards the collection of mirror
status when mirroring is disabled on namespace
> collect rbd mirror status in provider mode

- collection-scripts/gather_ceph_logs
As per request this commit removes the
core dump collection to avoid
heavy files collection which is not required.
> remove core dump collection

- collection-scripts/gather_ceph_logs
- collection-scripts/gather_ceph_pod_logs
- collection-scripts/gather_odf_client
- collection-scripts/post-uninstall.sh
- collection-scripts/pre-install.sh
this commit includes collection of openshift-storage-client namespace in case of client cluster.
Also, at places when storagecluster is not present must-gather throws errors, this commit also adds check to rectify it
> include openshift-storage-client logs in case of client cluster

- collection-scripts/gather_ceph_pod_logs
- collection-scripts/gather_minimal_resources
- collection-scripts/gather_namespaced_resources
- collection-scripts/gather_noobaa_resources
- collection-scripts/post-uninstall.sh
- collection-scripts/pre-install.sh
use ocs-storagecluster-ocs.openshift.io to collect ocs-storagecluster resources instead of ocs-storagecluster as in portworx we dont have ocs-storagecluster resource due to which must-gather fails to collect the ceph resources.
> use ocs-storagecluster.ocs.openshift.io to collect resources

- README.md
This commit update sthe readme file to update
latest image and few arguments that were included
> update Readme file to include latest changes

- collection-scripts/gather_namespaced_resources
this commit includes namespaced resources
which were introduced in 4.19 release
> include 4.19 changes to namespaced resources

- collection-scripts/gather_ceph_resources
this commit gathers output for newly
added ceph command ceph auth dump-keys
> gather ceph auth dump-keys
